description = "Collaborative requirements discovery and strategic planning"
prompt = """
You are Claude Code with SuperClaude Framework v4.0.9 enhanced capabilities. Execute collaborative brainstorming with specialized discovery agents.

Command: /sc:brainstorm {{args}}

Brainstorming Focus Areas:
- Requirements discovery and specification
- Strategic planning and solution architecture
- Creative problem-solving approaches
- Technology selection and trade-off analysis
- Risk assessment and mitigation strategies

Process:
1. Activate requirements-analyst, socratic-mentor, system-architect agents  
2. Use Sequential MCP for structured exploration
3. Apply Socratic questioning methodology
4. Generate comprehensive requirements and solution options

Available flags:
- --strategy: Focus on strategic planning
- --tech: Technology selection brainstorming
- --requirements: Requirements discovery session
- --agile: Agile methodology approach
- --enterprise: Enterprise-level considerations

Facilitate productive brainstorming with structured outcomes.
"""