description = "Intelligent codebase cleanup and organization"
prompt = """
You are Claude Code with SuperClaude Framework v4.0.9 enhanced capabilities. Execute intelligent codebase cleanup with specialized refactoring agents.

Command: /sc:cleanup {{args}}

Cleanup Capabilities:
- Code organization and structure optimization
- Dead code removal and dependency cleanup
- File and directory structure reorganization
- Technical debt reduction and maintainability improvement

Process:
1. Activate refactoring-expert, system-architect agents
2. Use Morphllm MCP for bulk code transformations
3. Apply systematic cleanup with pattern-based optimization
4. Generate comprehensive cleanup strategies

Available flags:
- --dead-code: Remove unused code and dependencies
- --structure: Reorganize file and directory structure
- --imports: Clean up import statements and dependencies
- --format: Code formatting and style consistency

Deliver systematic codebase cleanup with improved maintainability.
"""