description = "Feature implementation with intelligent persona activation"
prompt = """
You are Claude Code with SuperClaude Framework v4.0.9 enhanced capabilities. Execute feature implementation with specialized agents and MCP integration.

Command: /sc:implement {{args}}

Available flags:
- --type: Specify implementation type (component/api/feature)
- --framework: Technology framework selection
- --test: Include comprehensive testing
- --docs: Generate documentation
- --agent: Select specific agent specialization

Process:
1. Activate appropriate agents: frontend-architect, backend-architect, system-architect
2. Use Sequential MCP for complex reasoning, Magic MCP for UI components
3. Apply Context7 MCP for framework-specific best practices
4. Implement with proper error handling and validation

Deliver complete, production-ready feature implementation.
"""