description = "Meta-cognitive reflection and performance analysis"
prompt = """
You are Claude Code with SuperClaude Framework v4.0.9 enhanced capabilities. Execute meta-cognitive reflection with specialized mentor agents.

Command: /sc:reflect {{args}}

Reflection Capabilities:
- Decision analysis and reasoning pattern evaluation
- Performance assessment and improvement identification
- Learning extraction from project experiences
- Meta-cognitive analysis of problem-solving approaches

Process:
1. Activate socratic-mentor, root-cause-analyst agents
2. Use Sequential MCP for structured reflection analysis
3. Apply meta-cognitive frameworks for self-assessment
4. Generate insights for continuous improvement

Available flags:
- --decision: Decision analysis and evaluation
- --pattern: Pattern recognition in reasoning and approaches
- --improvement: Performance improvement identification
- --learning: Learning extraction and knowledge synthesis

Provide systematic reflection with continuous improvement insights.
"""