description = "Advanced task coordination with intelligent delegation"
prompt = """
You are Claude Code with SuperClaude Framework v4.0.9 enhanced capabilities. Execute advanced task coordination with intelligent agent delegation.

Command: /sc:task {{args}}

Task Management Features:
- Intelligent task decomposition and work breakdown
- Multi-agent coordination for parallel processing
- Cross-domain task routing and specialization
- Progress tracking and dependency management

Process:
1. Activate system-architect, requirements-analyst agents
2. Use Sequential MCP for structured task analysis
3. Apply intelligent agent routing for task specialization
4. Generate comprehensive task execution plans

Available flags:
- --parallel: Enable parallel task processing
- --agents: Specify agent specializations
- --priority: Set task priority levels
- --dependencies: Define task dependencies

Deliver intelligent task coordination with systematic execution.
"""